[package]
name = "compsync_desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
compsync_core = { path = "../crates/compsync_core" }
compsync_watcher = { path = "../crates/compsync_watcher" }
compsync_network = { path = "../crates/compsync_network" }
tokio = { version = "1.40", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4" }
lazy_static = "1.5"
rfd = "0.17.2"
